In [1]:
from skshapes.morphing import ElasticMetric
from skshapes.loss import OptimalTransportLoss
from skshapes.data import read
from skshapes.tasks import DistanceMatrix

/opt/conda/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
# Load some shapes
import os

datafolder = "/home/GitHub/scikit-shapes-draft/data/SCAPE/decimated/"
shapes = [read(os.path.join(datafolder, f"aligned_mesh{i:03d}.ply")) for i in range(4)]

dm = DistanceMatrix(
    model=ElasticMetric(),
    loss=OptimalTransportLoss(),
    verbose=1,
    n_iter=3,
    n_steps=5,
)

distance_matrix = dm.fit_transform(shapes=shapes)

Fitting shapes 0 and 1...
Loss value at iteration 0 : 0.0026407670229673386
Loss value at iteration 1 : 0.001409575343132019
Loss value at iteration 2 : 0.001409575343132019
Fitting shapes 0 and 2...
Loss value at iteration 0 : 0.007754892110824585
Loss value at iteration 1 : 0.0044431909918785095
Loss value at iteration 2 : 0.0044431909918785095
Fitting shapes 0 and 3...
Loss value at iteration 0 : 0.029282473027706146
Loss value at iteration 1 : 0.017379730939865112
Loss value at iteration 2 : 0.01489248313009739
Fitting shapes 1 and 2...
Loss value at iteration 0 : 0.013248100876808167
Loss value at iteration 1 : 0.00810194294899702
Loss value at iteration 2 : 0.005597298964858055
Fitting shapes 1 and 3...
Loss value at iteration 0 : 0.027684763073921204
Loss value at iteration 1 : 0.014586694538593292
Loss value at iteration 2 : 0.012402682565152645
Fitting shapes 2 and 3...
Loss value at iteration 0 : 0.03617389500141144
Loss value at iteration 1 : 0.01841193437576294
Loss value a

In [12]:
from sklearn.cluster import SpectralClustering

clustering = SpectralClustering(affinity="rbf", n_clusters=2).fit(distance_matrix)
print(clustering.labels_)

[0 0 0 1]


/opt/conda/lib/python3.8/site-packages/sklearn/cluster/_spectral.py:589: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(


In [1]:
from skshapes.preprocessing import (
    LandmarkSetter,
    Pipeline,
    Decimation,
    AffineTransformation,
)
from skshapes.data import read
import os

# Read the shapes
datafolder = "/home/GitHub/scikit-shapes-draft/data/SCAPE/decimated/"
shapes = [read(datafolder + "/" + f"aligned_mesh{i:03d}.ply") for i in range(4)]

# Create a pipeline of preprocessing steps
preprocessing = Pipeline(
    steps=[
        LandmarkSetter(landmarks=[[0, 1], [2, 3], [4, 5], [6, 70]], by_indices=True),
        Decimation(target_reduction=0.95),
        AffineTransformation(matrix=[[2, 0, 0], [0, 2, 0], [0, 0, 2]]),
    ]
)

# Apply the preprocessing pipeline to the shapes and get the dataset
dataset = preprocessing.fit_transform(shapes=shapes)

for i in range(len(dataset)):
    print("Size of shape {} : {}".format(i, dataset[i].points.shape))
    print("Landmarks of shape {} : {}".format(i, dataset.landmarks[i]), end="\n\n")

Size of shape 0 : torch.Size([518, 3])
Landmarks of shape 0 : tensor([[ 0.0156, -0.0755,  0.2701],
        [ 0.0190,  0.0418,  0.2677]])

Size of shape 1 : torch.Size([446, 3])
Landmarks of shape 1 : tensor([[0.0314, 0.0201, 0.2025],
        [0.0319, 0.0535, 0.1964]])

Size of shape 2 : torch.Size([465, 3])
Landmarks of shape 2 : tensor([[-0.0111,  0.0480,  0.1389],
        [-0.0108, -0.0148,  0.1165]])

Size of shape 3 : torch.Size([444, 3])
Landmarks of shape 3 : tensor([[ 0.0917, -0.3005,  0.1144],
        [ 0.0360,  0.2349,  0.0129]])



In [8]:
t = dataset.landmarks[0]
list(t)

[tensor([ 0.0156, -0.0755,  0.2701]), tensor([0.0190, 0.0418, 0.2677])]

In [68]:
import pyvista
import numpy as np

polydata = pyvista.read(os.path.join(datafolder, f"aligned_mesh008.ply"))
old_points = polydata.points.copy()
polydata.decimate_pro(0.999, preserve_topology=True, inplace=True)
new_points = polydata.points.copy()

[
    np.where(np.all(new_points[i] == old_points, axis=1))[0][0]
    for i in range(len(new_points))
]

[4,
 5,
 8,
 9,
 10,
 12,
 14,
 15,
 16,
 17,
 18,
 20,
 21,
 24,
 25,
 26,
 27,
 30,
 32,
 34,
 35,
 36,
 39,
 41,
 42,
 44,
 45,
 46,
 49,
 50,
 53,
 55,
 56,
 57,
 60,
 62,
 64,
 66,
 67,
 69,
 70,
 71,
 73,
 74,
 75,
 77,
 79,
 80,
 81,
 85,
 86,
 87,
 88,
 89,
 90,
 94,
 95,
 96,
 97,
 98,
 100,
 101,
 104,
 105,
 106,
 108,
 110,
 111,
 112,
 113,
 115,
 116,
 119,
 125,
 135,
 138,
 139,
 141,
 145,
 151,
 152,
 155,
 159,
 165,
 166,
 169,
 173,
 177,
 178,
 181,
 182,
 185,
 187,
 199,
 204,
 213,
 214,
 216,
 217,
 219,
 240,
 241,
 243,
 244,
 247,
 252,
 259,
 266,
 267,
 270,
 273,
 279,
 280,
 284,
 290,
 296,
 298,
 300,
 313,
 319,
 328,
 344,
 351,
 359,
 366,
 367,
 378,
 390,
 404,
 414,
 424,
 443,
 451,
 470,
 486,
 487,
 495,
 499,
 500,
 504,
 512,
 524,
 529,
 537,
 539,
 540,
 545,
 546,
 552,
 556,
 566,
 587,
 588,
 602,
 608,
 609,
 613,
 618,
 619,
 620,
 624,
 627,
 629,
 630,
 632,
 633,
 634,
 637,
 639,
 644,
 647,
 650,
 651,
 653,
 654,
 656,
 657,
 6

In [5]:
shape = shapes[0]
pv_shape = shape.to_pyvista()

from skshapes.data import Shape

shape2 = Shape.from_pyvista(pv_shape)

In [9]:
shape.edges

tensor([[ 864,  871,  842,  ..., 1558, 1560, 1561],
        [ 871,  842,  864,  ..., 1559, 1561, 1559]])

In [65]:
print(new_points.shape)
print(old_points.shape)

(472, 3)
(1562, 3)


In [27]:
import torch
import numpy as np

landmarks = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
landmarks = np.array(
    [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
)

if not isinstance(landmarks, torch.Tensor):
    landmarks = torch.tensor(landmarks)


if landmarks.is_floating_point():
    dtype = landmarks.dtype
    if torch.all(landmarks == landmarks.long().to(dtype=dtype)):
        landmarks = landmarks.long()

landmarks

/tmp/ipykernel_177429/1833343818.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  landmarks = torch.tensor(c)


tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]])

In [1]:
"""3D slider to move a mesh interactively"""
from vedo import Plotter, Mesh, dataurl, settings

settings.default_backend = "vtk"


plt = Plotter()

mesh = Mesh(dataurl + "spider.ply")
mesh.normalize().rotate_z(190)


def slider_y(widget, event):
    mesh.y(widget.value)  # set y coordinate position


plt.add_slider3d(
    slider_y,
    pos1=[0.5, -3.5, 0.35],
    pos2=[0.5, -1.0, 0.35],
    xmin=-1,
    xmax=1,
    value=0,
    s=0.04,
    c="r",
    rotation=45,
    title="y position",
)

plt.show(mesh, __doc__, axes=11, bg="bb", bg2="navy")
plt.close()

: 

: 