In [3]:
from skshapes.morphing import ElasticMetric, RigidMotion
from skshapes.loss import OptimalTransportLoss, LandmarkLoss, NearestNeighborsLoss
from skshapes.data import read
from skshapes.tasks import DistanceMatrix, Registration
import torch

In [10]:
import os

targetfolder = "data/SCAPE_low_resolution_aligned"
datafolder = "data/SCAPE_low_resolution"

files = os.listdir(datafolder)
reference = read(datafolder + "/" + files[0])
rest = [read(datafolder + "/" + file) for file in files[1:]]

N = reference.points.shape[0]
reference.landmarks = torch.arange(N, dtype=torch.int64)
reference.to_pyvista().save(targetfolder + "/" + files[0])

for i, mesh in enumerate(rest):
    print("Aligning " + files[i + 1] + " to " + files[0] + "...")
    mesh.landmarks = torch.arange(N, dtype=torch.int64)

    r = Registration(
        model=RigidMotion(),
        loss=LandmarkLoss(p=2),
        verbose=0,
        n_iter=5,
        device="cuda:0",
    )

    morphed = r.fit_transform(source=mesh, target=reference)
    morphed.to_pyvista().save(targetfolder + "/" + files[i + 1])

Aligning mesh005.ply to mesh047.ply...
Aligning mesh001.ply to mesh047.ply...
Aligning mesh042.ply to mesh047.ply...
Aligning mesh027.ply to mesh047.ply...
Aligning mesh003.ply to mesh047.ply...
Aligning mesh023.ply to mesh047.ply...
Aligning mesh026.ply to mesh047.ply...
Aligning mesh022.ply to mesh047.ply...
Aligning mesh028.ply to mesh047.ply...
Aligning mesh033.ply to mesh047.ply...
Aligning mesh021.ply to mesh047.ply...
Aligning mesh044.ply to mesh047.ply...
Aligning mesh004.ply to mesh047.ply...
Aligning mesh024.ply to mesh047.ply...
Aligning mesh070.ply to mesh047.ply...
Aligning mesh029.ply to mesh047.ply...
Aligning mesh034.ply to mesh047.ply...
Aligning mesh011.ply to mesh047.ply...
Aligning mesh048.ply to mesh047.ply...
Aligning mesh012.ply to mesh047.ply...
Aligning mesh068.ply to mesh047.ply...
Aligning mesh052.ply to mesh047.ply...
Aligning mesh000.ply to mesh047.ply...
Aligning mesh065.ply to mesh047.ply...
Aligning mesh018.ply to mesh047.ply...
Aligning mesh032.ply to m

In [4]:
import os

targetfolder = "data/SCAPE_low_resolution_aligned_ICP"
datafolder = "data/SCAPE_low_resolution"

files = os.listdir(datafolder)
reference = read(datafolder + "/" + files[0])
rest = [read(datafolder + "/" + file) for file in files[1:]]

reference.to_pyvista().save(targetfolder + "/" + files[0])

for i, mesh in enumerate(rest):
    print("Aligning " + files[i + 1] + " to " + files[0] + "...")

    r = Registration(
        model=RigidMotion(),
        loss=NearestNeighborsLoss(),
        verbose=0,
        n_iter=5,
        device="cuda:0",
    )

    morphed = r.fit_transform(source=mesh, target=reference)
    morphed.to_pyvista().save(targetfolder + "/" + files[i + 1])

Aligning mesh005.ply to mesh047.ply...
[KeOps] Generating code for formula ArgKMin_Reduction(Sum((Var(0,3,0)-Var(1,3,1))**2),0) ... OK
[pyKeOps] Warning : at least one of the input tensors is not contiguous. Consider using contiguous data arrays to avoid unnecessary copies.
[pyKeOps] Warning : at least one of the input tensors is not contiguous. Consider using contiguous data arrays to avoid unnecessary copies.
[pyKeOps] Warning : at least one of the input tensors is not contiguous. Consider using contiguous data arrays to avoid unnecessary copies.
[pyKeOps] Warning : at least one of the input tensors is not contiguous. Consider using contiguous data arrays to avoid unnecessary copies.
[pyKeOps] Warning : at least one of the input tensors is not contiguous. Consider using contiguous data arrays to avoid unnecessary copies.
[pyKeOps] Warning : at least one of the input tensors is not contiguous. Consider using contiguous data arrays to avoid unnecessary copies.
[pyKeOps] Warning : at le

In [25]:
from pykeops.torch import Vi, Vj

reference = torch.randn(100, 3)
target = torch.randn(200, 3)

X_i = Vi(reference)
X_j = Vj(target)

D_ij = ((X_i - X_j) ** 2).sum(-1)
correspondences = D_ij.argKmin(K=1, dim=1).view(-1)

torch.norm((reference - target[correspondences]), p=2, dim=1).mean()

tensor(0.4216)

In [8]:
import os

datafolder = "data/SCAPE_low_resolution"

os.listdir(datafolder)

['mesh047.ply',
 'mesh005.ply',
 'mesh001.ply',
 'mesh042.ply',
 'mesh027.ply',
 'mesh003.ply',
 'mesh023.ply',
 'mesh026.ply',
 'mesh022.ply',
 'mesh028.ply',
 'mesh033.ply',
 'mesh021.ply',
 'mesh044.ply',
 'mesh004.ply',
 'mesh024.ply',
 'mesh070.ply',
 'mesh029.ply',
 'mesh034.ply',
 'mesh011.ply',
 'mesh048.ply',
 'mesh012.ply',
 'mesh068.ply',
 'mesh052.ply',
 'mesh000.ply',
 'mesh065.ply',
 'mesh018.ply',
 'mesh032.ply',
 'mesh046.ply',
 'mesh038.ply',
 'mesh017.ply',
 'mesh025.ply',
 'mesh040.ply',
 'mesh036.ply',
 'mesh016.ply',
 'mesh010.ply',
 'mesh064.ply',
 'mesh057.ply',
 'mesh041.ply',
 'mesh058.ply',
 'mesh030.ply',
 'mesh069.ply',
 'mesh056.ply',
 'mesh009.ply',
 'mesh054.ply',
 'mesh060.ply',
 'mesh053.ply',
 'mesh071.ply',
 'mesh002.ply',
 'mesh063.ply',
 'mesh019.ply',
 'mesh045.ply',
 'mesh043.ply',
 'mesh020.ply',
 'mesh037.ply',
 'mesh067.ply',
 'mesh050.ply',
 'mesh007.ply',
 'mesh061.ply',
 'mesh049.ply',
 'mesh066.ply',
 'mesh013.ply',
 'mesh035.ply',
 'mesh01

In [7]:
# Load some shapes
import os

datafolder = "/home/GitHub/scikit-shapes-draft/data/SCAPE/decimated/"
datafolder = "data/SCAPE_low_resolution"


shapes = [read(datafolder + "/" + f"mesh{i:03d}.ply") for i in range(10)]

r = Registration(
    model=ElasticMetric(n_steps=5),
    loss=OptimalTransportLoss(),
    verbose=1,
    n_iter=10,
    regularization=0,
)

r.fit(source=shapes[0], target=shapes[7])
newshape = r.transform(source=shapes[0])

Loss value at iteration 0 : 0.15649539232254028
Loss value at iteration 1 : 0.01606137678027153
Loss value at iteration 2 : 0.007564371917396784
Loss value at iteration 3 : 0.005975775420665741
Loss value at iteration 4 : 0.005975562613457441
Loss value at iteration 5 : 0.005975562147796154
Loss value at iteration 6 : 0.005975562147796154
Loss value at iteration 7 : 0.005975562147796154
Loss value at iteration 8 : 0.005975562147796154
Loss value at iteration 9 : 0.005975562147796154


In [6]:
newshape.to_pyvista().save("newshape.vtk")

In [19]:
from sklearn.cluster import SpectralClustering
import numpy as np

affinity_matrix = np.exp(-((distance_matrix / 0.001) ** 2))

clustering = SpectralClustering(affinity="precomputed", n_clusters=2).fit(
    affinity_matrix
)
print(clustering.labels_)

[0 0 0 0 0 0 1 0 1 0]


In [1]:
from skshapes.preprocessing import (
    LandmarkSetter,
    Pipeline,
    Decimation,
    AffineTransformation,
)
from skshapes.data import read
import os

# Read the shapes
datafolder = "/home/GitHub/scikit-shapes-draft/data/SCAPE/decimated/"
shapes = [read(datafolder + "/" + f"aligned_mesh{i:03d}.ply") for i in range(4)]

# Create a pipeline of preprocessing steps
preprocessing = Pipeline(
    steps=[
        LandmarkSetter(landmarks=[[0, 1], [2, 3], [4, 5], [6, 70]], by_indices=True),
        Decimation(target_reduction=0.95),
        AffineTransformation(matrix=[[2, 0, 0], [0, 2, 0], [0, 0, 2]]),
    ]
)

# Apply the preprocessing pipeline to the shapes and get the dataset
dataset = preprocessing.fit_transform(shapes=shapes)

for i in range(len(dataset)):
    print("Size of shape {} : {}".format(i, dataset[i].points.shape))
    print("Landmarks of shape {} : {}".format(i, dataset.landmarks[i]), end="\n\n")

Size of shape 0 : torch.Size([518, 3])
Landmarks of shape 0 : tensor([[ 0.0156, -0.0755,  0.2701],
        [ 0.0190,  0.0418,  0.2677]])

Size of shape 1 : torch.Size([446, 3])
Landmarks of shape 1 : tensor([[0.0314, 0.0201, 0.2025],
        [0.0319, 0.0535, 0.1964]])

Size of shape 2 : torch.Size([465, 3])
Landmarks of shape 2 : tensor([[-0.0111,  0.0480,  0.1389],
        [-0.0108, -0.0148,  0.1165]])

Size of shape 3 : torch.Size([444, 3])
Landmarks of shape 3 : tensor([[ 0.0917, -0.3005,  0.1144],
        [ 0.0360,  0.2349,  0.0129]])



In [8]:
t = dataset.landmarks[0]
list(t)

[tensor([ 0.0156, -0.0755,  0.2701]), tensor([0.0190, 0.0418, 0.2677])]

In [68]:
import pyvista
import numpy as np

polydata = pyvista.read(os.path.join(datafolder, f"aligned_mesh008.ply"))
old_points = polydata.points.copy()
polydata.decimate_pro(0.999, preserve_topology=True, inplace=True)
new_points = polydata.points.copy()

[
    np.where(np.all(new_points[i] == old_points, axis=1))[0][0]
    for i in range(len(new_points))
]

[4,
 5,
 8,
 9,
 10,
 12,
 14,
 15,
 16,
 17,
 18,
 20,
 21,
 24,
 25,
 26,
 27,
 30,
 32,
 34,
 35,
 36,
 39,
 41,
 42,
 44,
 45,
 46,
 49,
 50,
 53,
 55,
 56,
 57,
 60,
 62,
 64,
 66,
 67,
 69,
 70,
 71,
 73,
 74,
 75,
 77,
 79,
 80,
 81,
 85,
 86,
 87,
 88,
 89,
 90,
 94,
 95,
 96,
 97,
 98,
 100,
 101,
 104,
 105,
 106,
 108,
 110,
 111,
 112,
 113,
 115,
 116,
 119,
 125,
 135,
 138,
 139,
 141,
 145,
 151,
 152,
 155,
 159,
 165,
 166,
 169,
 173,
 177,
 178,
 181,
 182,
 185,
 187,
 199,
 204,
 213,
 214,
 216,
 217,
 219,
 240,
 241,
 243,
 244,
 247,
 252,
 259,
 266,
 267,
 270,
 273,
 279,
 280,
 284,
 290,
 296,
 298,
 300,
 313,
 319,
 328,
 344,
 351,
 359,
 366,
 367,
 378,
 390,
 404,
 414,
 424,
 443,
 451,
 470,
 486,
 487,
 495,
 499,
 500,
 504,
 512,
 524,
 529,
 537,
 539,
 540,
 545,
 546,
 552,
 556,
 566,
 587,
 588,
 602,
 608,
 609,
 613,
 618,
 619,
 620,
 624,
 627,
 629,
 630,
 632,
 633,
 634,
 637,
 639,
 644,
 647,
 650,
 651,
 653,
 654,
 656,
 657,
 6

In [5]:
shape = shapes[0]
pv_shape = shape.to_pyvista()

from skshapes.data import Shape

shape2 = Shape.from_pyvista(pv_shape)

In [9]:
shape.edges

tensor([[ 864,  871,  842,  ..., 1558, 1560, 1561],
        [ 871,  842,  864,  ..., 1559, 1561, 1559]])

In [65]:
print(new_points.shape)
print(old_points.shape)

(472, 3)
(1562, 3)


In [27]:
import torch
import numpy as np

landmarks = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
landmarks = np.array(
    [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
)

if not isinstance(landmarks, torch.Tensor):
    landmarks = torch.tensor(landmarks)


if landmarks.is_floating_point():
    dtype = landmarks.dtype
    if torch.all(landmarks == landmarks.long().to(dtype=dtype)):
        landmarks = landmarks.long()

landmarks

/tmp/ipykernel_177429/1833343818.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  landmarks = torch.tensor(c)


tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]])

In [1]:
"""3D slider to move a mesh interactively"""
from vedo import Plotter, Mesh, dataurl, settings

settings.default_backend = "vtk"


plt = Plotter()

mesh = Mesh(dataurl + "spider.ply")
mesh.normalize().rotate_z(190)


def slider_y(widget, event):
    mesh.y(widget.value)  # set y coordinate position


plt.add_slider3d(
    slider_y,
    pos1=[0.5, -3.5, 0.35],
    pos2=[0.5, -1.0, 0.35],
    xmin=-1,
    xmax=1,
    value=0,
    s=0.04,
    c="r",
    rotation=45,
    title="y position",
)

plt.show(mesh, __doc__, axes=11, bg="bb", bg2="navy")
plt.close()

: 

: 